### PR TITLE
Fix installation instructions

### PR DESCRIPTION
**Pull request by di3goleite**
You must need give permission for this script execute.

### CODE REVIEW

**Comment by denysdovhan** [comment]
I think it seems reasonable.

@kbytin are you maintain this project? What do you think?

**Comment by maxclaus** [comment]
Instead of requiring every user to follow these steps I think a solution as the one used by **oh-my-zsh** is better. There is no need to make the file executable and does not create a temp file.
https://github.com/robbyrussell/oh-my-zsh/#basic-installation

Example:

``` bash
bash -c "$(curl -fsSL https://raw.githubusercontent.com/denysdovhan/gnome-terminal-one/master/one-dark.sh)"
```

**Comment by denysdovhan** [comment]
@maxcnunes file shouldn't be just executed, it should be _sourced_. Could you please open new PR with you proposal and sourcing theme's file?

**Comment by denysdovhan** [comment]
I close this PR, since @maxcnunes provide a better solution. Would be cool to see a PR with that solution. Gonna merge that one.

**Pull request closed without merging**
